crowdin: Track omni style and slim recent
ResurrectionRemix/platform_manifest pull request #111
Opened 2018-02-15 19:21 UTC by jhenrique09

2018-02-15 23:51 UTC, varund7726 commented
There are no strings there yet .

2018-02-16 04:32 UTC, akhilnarang requested changes

2018-02-16 04:32 UTC, akhilnarang commented on crowdin.xml
> +  <project name="android_packages_apps_OmniStyle" path="packages/apps/OmniStyle" remote="rr" />
Added twice

2018-02-16 04:57 UTC, varund7726 commented
No need for omnistyle .we won't modify it anyways .slim regents we might need but not as of now

2018-02-16 04:57 UTC, closed without merging